#!/usr/bin/env python3
"""
sync_claude_md.py
-----------------
Fetches the current memory snapshot from the memoryOS backend and writes
(or updates) CLAUDE.md in the target project root.

Claude Code reads CLAUDE.md automatically at the start of every session,
so this gives Claude persistent context without any manual re-explaining.

Usage
-----
  # Sync to the current working directory (default)
  python scripts/sync_claude_md.py

  # Sync to a specific project root
  python scripts/sync_claude_md.py --project /path/to/your/project

  # Use a specific agent ID
  python scripts/sync_claude_md.py --agent-id my-project-agent

  # Use a different backend URL
  python scripts/sync_claude_md.py --url http://localhost:8000

Environment variables (all optional, override with CLI flags)
-----
  MEMORY_OS_URL       — backend URL         (default: http://localhost:8000)
  MEMORY_OS_AGENT_ID  — agent/user identity (default: claude-code)
  MEMORY_OS_PROJECT   — project root dir    (default: cwd)
"""

import argparse
import json
import os
import sys
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

DEFAULT_URL = os.getenv("MEMORY_OS_URL", "http://localhost:8000")
DEFAULT_AGENT = os.getenv("MEMORY_OS_AGENT_ID", "claude-code")
DEFAULT_PROJECT = os.getenv("MEMORY_OS_PROJECT", os.getcwd())

CLAUDE_MD_HEADER = """\
<!--
  This file is auto-generated by memoryOS (scripts/sync_claude_md.py).
  Do NOT edit manually — your edits will be overwritten on the next sync.
  To add persistent context, tell Claude directly and it will store it.

  Generated: {generated_at}
  Agent ID:  {agent_id}
  Backend:   {backend_url}
-->

# Claude Memory Context

> This file gives Claude Code persistent memory across sessions.
> It is auto-synced from memoryOS. Last update: {generated_at}

"""


def fetch_snapshot(url: str, agent_id: str) -> dict:
    endpoint = url.rstrip("/") + "/api/context/snapshot"
    full_url = endpoint + "?" + urllib.parse.urlencode({"agent_id": agent_id})
    try:
        with urllib.request.urlopen(full_url, timeout=10) as resp:
            return json.loads(resp.read().decode())
    except urllib.error.URLError as e:
        print(f"[sync_claude_md] Cannot reach memoryOS backend at {url}: {e}", file=sys.stderr)
        sys.exit(1)


def _conf_badge(conf: float) -> str:
    if conf >= 0.8:
        return "●●●"
    if conf >= 0.5:
        return "●●○"
    return "●○○"


def _age_str(age_hours: float) -> str:
    if age_hours < 1:
        return "< 1h ago"
    if age_hours < 24:
        return f"{age_hours:.0f}h ago"
    days = age_hours / 24
    if days < 7:
        return f"{days:.0f}d ago"
    return f"{days/7:.0f}w ago"


def render_claude_md(snapshot: dict, backend_url: str) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    agent_id = snapshot.get("agent_id", "unknown")
    profile = snapshot.get("profile", [])
    project = snapshot.get("project", [])
    workflow = snapshot.get("workflow", [])
    working = snapshot.get("working_memory")

    lines: list[str] = []
    lines.append(
        CLAUDE_MD_HEADER.format(
            generated_at=now,
            agent_id=agent_id,
            backend_url=backend_url,
        )
    )

    # --- Who I Am ---
    lines.append("## Who I Am\n")
    if profile:
        for m in profile:
            badge = _conf_badge(m["confidence"])
            lines.append(f"- {badge} {m['content']}")
    else:
        lines.append("- *(No profile context stored yet — tell Claude about yourself!)*")
    lines.append("")

    # --- Current Task ---
    lines.append("## Current Task\n")
    if working and working.get("task"):
        pct = working.get("progress_pct", 0)
        bar_filled = int(pct / 10)
        bar = "█" * bar_filled + "░" * (10 - bar_filled)
        lines.append(f"**{working['task']}**")
        lines.append(f"Progress: [{bar}] {pct:.0f}%")
        if working.get("last_action"):
            lines.append(f"Last action: {working['last_action']}")
    else:
        lines.append("- *(No active task tracked)*")
    lines.append("")

    # --- This Project ---
    lines.append("## This Project\n")
    if project:
        # Group by category
        decisions = [m for m in project if m["category"] == "project_decision"]
        knowledge = [m for m in project if m["category"] == "codebase_knowledge"]
        if decisions:
            lines.append("**Decisions made:**")
            for m in decisions:
                age = _age_str(m["age_hours"])
                badge = _conf_badge(m["confidence"])
                lines.append(f"- {badge} {m['content']}  *({age})*")
            lines.append("")
        if knowledge:
            lines.append("**Codebase knowledge:**")
            for m in knowledge:
                badge = _conf_badge(m["confidence"])
                lines.append(f"- {badge} {m['content']}")
    else:
        lines.append("- *(No project decisions stored yet)*")
    lines.append("")

    # --- How I Work ---
    lines.append("## How I Work\n")
    if workflow:
        for m in workflow:
            badge = _conf_badge(m["confidence"])
            lines.append(f"- {badge} {m['content']}")
    else:
        lines.append("- *(No workflow patterns stored yet)*")
    lines.append("")

    # --- Instructions for Claude ---
    lines.append("## Instructions for Claude\n")
    lines.append(
        "- Use the `recall` memory tool to search for additional context before answering."
    )
    lines.append(
        "- Use the `remember` tool to store new facts the developer shares."
    )
    lines.append(
        "- When the user shares multiple pieces of information in a single message, break them down into separate ATOMIC facts and pass them all at once in the `facts` array."
    )
    lines.append(
        "- Use `get_my_profile` and `get_project_context` tools at the start of each session."
    )
    lines.append(
        "- When you detect a contradiction with stored context, raise it explicitly."
    )
    lines.append(
        "- Confidence scores decay over time — lower scores mean older/less certain facts."
    )
    lines.append("")

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Sync memoryOS snapshot to CLAUDE.md for passive context injection."
    )
    parser.add_argument("--url", default=DEFAULT_URL, help="memoryOS backend URL")
    parser.add_argument("--agent-id", default=DEFAULT_AGENT, help="Agent/user identity")
    parser.add_argument(
        "--project",
        default=DEFAULT_PROJECT,
        help="Project root where CLAUDE.md will be written",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the generated CLAUDE.md without writing it",
    )
    args = parser.parse_args()

    print(f"[sync_claude_md] Fetching snapshot for agent '{args.agent_id}' from {args.url}...")
    snapshot = fetch_snapshot(args.url, args.agent_id)

    profile_count = len(snapshot.get("profile", []))
    project_count = len(snapshot.get("project", []))
    workflow_count = len(snapshot.get("workflow", []))
    print(
        f"[sync_claude_md] Got {profile_count} profile, "
        f"{project_count} project, {workflow_count} workflow memories."
    )

    content = render_claude_md(snapshot, args.url)

    if args.dry_run:
        print("\n--- CLAUDE.md (dry run) ---")
        print(content)
        return

    output_path = Path(args.project) / "CLAUDE.md"
    output_path.write_text(content, encoding="utf-8")
    print(f"[sync_claude_md] Written to {output_path}")


if __name__ == "__main__":
    main()
